#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<-EOSQL

CREATE SCHEMA IF NOT EXISTS opinions AUTHORIZATION $POSTGRES_USER;
CREATE SCHEMA IF NOT EXISTS users AUTHORIZATION $POSTGRES_USER;
CREATE SCHEMA IF NOT EXISTS mock AUTHORIZATION $POSTGRES_USER;

EOSQL