x-tls-common-env: &tls-common-env
  SERVER_SSL_ENABLED: ${SERVER_SSL_ENABLED:?}
  SERVER_SSL_KEY_STORE_PASSWORD: ${TLS_KEYSTORE_PASSWORD:?}
  SERVER_SSL_KEY_STORE_TYPE: PKCS12
  SERVER_SSL_KEY_ALIAS: ${SERVER_SSL_KEY_ALIAS:?}

services:
  database:
    image: postgres:15
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME:?}
      POSTGRES_USER: ${DATABASE_USERNAME:?}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?}
    ports:
      - "${DATABASE_HOST_PORT:?}:${DATABASE_CONTAINER_PORT:?}"
    volumes:
      - ./deployment/database/data:/var/lib/postgresql/data
      - ./deployment/database/init:/docker-entrypoint-initdb.d
    networks:
      - r8n_net

  opinions:
    build:
      context: ./deployment/opinions
      dockerfile: Dockerfile
    env_file:
      - ./deployment/config/docker.env
      - ./deployment/secrets/docker.secrets.env
    environment:
      SPRING_PROFILES_ACTIVE: local
      <<: *tls-common-env
      SERVICE_NAME: opinions
      SERVER_SSL_KEY_STORE: /certs/keystore-opinions.p12
      SERVICES_OPINIONS_PORT: ${SERVICES_OPINIONS_PORT:?}
      LOGGING_FILE_NAME: ${LOGGING_FILE_NAME:?}
    networks:
      - r8n_net
    volumes:
      - ./deployment/opinions/logs:/var/log/r8n
      - ./deployment/certs:/certs:ro

  mock:
    build:
      context: ./deployment/mock
      dockerfile: Dockerfile
    env_file:
      - ./deployment/config/docker.env
      - ./deployment/secrets/docker.secrets.env
    environment:
      <<: *tls-common-env
      SERVICE_NAME: mock
      SERVER_SSL_KEY_STORE: /certs/keystore-mock.p12
      SERVICES_MOCK_PORT: ${SERVICES_MOCK_PORT:?}
      LOGGING_FILE_NAME: ${LOGGING_FILE_NAME:?}
    networks:
      - r8n_net
    volumes:
      - ./deployment/mock/logs:/var/log/r8n
      - ./deployment/certs:/certs:ro

  gateway:
    build:
      context: ./deployment/gateway
      dockerfile: Dockerfile
    env_file:
      - ./deployment/config/docker.env
      - ./deployment/secrets/docker.secrets.env
    environment:
      <<: *tls-common-env
      SERVICE_NAME: gateway
      SERVER_SSL_KEY_STORE: /certs/keystore-gateway.p12
      GATEWAY_PORT: ${GATEWAY_CONTAINER_PORT:?}
      GATEWAY_HOST_PORT: ${GATEWAY_HOST_PORT:?}
      INTERSERVICE_PROTOCOL: ${INTERSERVICE_PROTOCOL:?}
      SERVICES_OPINIONS_HOST: ${SERVICES_OPINIONS_HOST:?}
      SERVICES_OPINIONS_PORT: ${SERVICES_OPINIONS_PORT:?}
      SERVICES_MOCK_HOST: ${SERVICES_MOCK_HOST:?}
      SERVICES_MOCK_PORT: ${SERVICES_MOCK_PORT:?}
      LOGGING_FILE_NAME: ${LOGGING_FILE_NAME:?}

      JAVA_TOOL_OPTIONS: >-
        -Djavax.net.ssl.trustStore=${SSL_TRUST_STORE:?}
        -Djavax.net.ssl.trustStorePassword=${TLS_TRUSTSTORE_PASSWORD:?}
        -Djavax.net.ssl.trustStoreType=PKCS12
    ports:
      - "${GATEWAY_HOST_PORT:?}:${GATEWAY_CONTAINER_PORT:?}"
    depends_on:
      - opinions
      - mock
      - database
    networks:
      - r8n_net
    volumes:
      - ./deployment/gateway/logs:/var/log/r8n
      - ./deployment/certs:/certs:ro

  frontend:
    build:
      context: .
      dockerfile: deployment/frontend/Dockerfile
    depends_on:
      - gateway
    ports:
      - "${FRONTEND_HTTP_HOST_PORT:?}:80"
      - "${FRONTEND_HTTPS_HOST_PORT:?}:443"
    volumes:
      - ./deployment/certs:/etc/nginx/certs:ro
    networks:
      - r8n_net

networks:
  r8n_net:
    name: r8n_net
    driver: bridge
