spring:
  application.name: opinions-sv
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/local
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${SERVICES_OPINIONS_PORT:8081}
