server.port: ${SERVICES_OPINIONS_PORT:8081}
spring:
  application.name: opinions-sv
  liquibase:
    change-log: db/changelog/db.changelog-master.sql

  datasource:
    driver-class-name: org.postgresql.Driver
services:
  users:
    url: ${INTERSERVICE_PROTOCOL:http}://${SERVICES_USERS_HOST:localhost}:${SERVICES_USERS_PORT:8082}
