/*
 * This source file was generated by the Gradle 'init' task
 */
package com.r8n.backend.gateway;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GatewayApplicationTest {
    @Test void appHasAGreeting() {
        GatewayApplication classUnderTest = new GatewayApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
