server:
  port: ${SERVICES_USERS_PORT:8082}
  ssl:
    enabled: ${SERVER_SSL_ENABLED:false}
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE:PKCS12}
    key-alias: ${SERVER_SSL_KEY_ALIAS}
spring:
  application.name: users-sv
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.sql
    default-schema: users

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_HOST_PORT}/${DATABASE_NAME}?currentSchema=users
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
services:
  mock:
    url: ${INTERSERVICE_PROTOCOL:http}://${SERVICES_MOCK_HOST:localhost}:${SERVICES_MOCK_PORT:8090}
r8n:
  security:
    jwt:
      private-key: ${JWT_PRIVATE_KEY}
      public-key: ${JWT_PUBLIC_KEY}
