server.port: ${SERVICES_USERS_PORT:8082}
spring:
  application.name: users-sv
  liquibase:
    change-log: db/changelog/db.changelog-master.sql
  datasource:
    driver-class-name: org.postgresql.Driver
services:
  mock:
    url: ${INTERSERVICE_PROTOCOL:http}://${SERVICES_MOCK_HOST:localhost}:${SERVICES_MOCK_PORT:8090}
r8n:
  security:
    jwt:
      public-key: ${JWT_PUBLIC_KEY}
