server:
  port: ${SERVICES_USERS_PORT}
  ssl:
    enabled: ${SERVER_SSL_ENABLED}
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE}
    key-alias: ${SERVER_SSL_KEY_ALIAS}
spring:
  application.name: users-sv
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.sql
    default-schema: users

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_HOST_PORT}/${DATABASE_NAME}?currentSchema=users
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: never
services:
  mock:
    url: ${INTERSERVICE_PROTOCOL}://${SERVICES_MOCK_HOST}:${SERVICES_MOCK_PORT}
r8n:
  security:
    public-paths: /auth/**
    jwt:
      private-key: ${JWT_PRIVATE_KEY}
      public-key: ${JWT_PUBLIC_KEY}
    refresh-cookie:
      secure: ${SERVER_SSL_ENABLED}
      same-site: Strict
      path: /auth
      max-age: ${R8N_SECURITY_REFRESH_COOKIE_MAX_AGE:30d}
