server:
  port: ${GATEWAY_PORT}
  ssl:
    enabled: ${SERVER_SSL_ENABLED}
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE}
    key-alias: ${SERVER_SSL_KEY_ALIAS}

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: opinions
              uri: ${INTERSERVICE_PROTOCOL}://${SERVICES_OPINIONS_HOST}:${SERVICES_OPINIONS_PORT}
              predicates:
                - Path=/opinions/**
            - id: mock
              uri: ${INTERSERVICE_PROTOCOL}://${SERVICES_MOCK_HOST}:${SERVICES_MOCK_PORT}
              predicates:
                - Path=/auth/**,/accessRequests/**,/opinionLists/**,/selectors/**
