server.port: ${SERVICES_EXPORT_PORT}

spring:
  application.name: export-sv

services:
  users:
    url: ${INTERSERVICE_PROTOCOL}://${SERVICES_USERS_HOST}:${SERVICES_USERS_PORT}

r8n:
  security:
    jwt:
      public-key: ${JWT_PUBLIC_KEY}
