spring:
  application:
    name: export-sv
server:
  port: ${SERVICES_EXPORT_PORT}
services:
  users:
    url: ${INTERSERVICE_PROTOCOL}://${SERVICES_USERS_HOST}:${SERVICES_USERS_PORT}
  mock:
    url: ${INTERSERVICE_PROTOCOL}://${SERVICES_MOCK_HOST}:${SERVICES_MOCK_PORT}
logging:
  level:
    com.r8n.backend.security: DEBUG
    org.springframework.web.client: DEBUG