spring:
  application.name: mock-sv
  liquibase:
    enabled: true
    change-log: db/changelog/mock/db.changelog-master.sql
    default-schema: mock
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_HOST_PORT}/${DATABASE_NAME}?currentSchema=mock
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: never
server:
  port: ${SERVICES_MOCK_PORT}
  ssl:
    enabled: ${SERVER_SSL_ENABLED}
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE}
    key-alias: ${SERVER_SSL_KEY_ALIAS}
r8n:
  security:
    jwt:
      private-key: ${JWT_PRIVATE_KEY}
      public-key: ${JWT_PUBLIC_KEY}
