spring:
  application.name: access-sv
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql
server:
  port: ${SERVICES_ACCESS_PORT}
  ssl:
    enabled: ${SERVER_SSL_ENABLED}
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE}
    key-alias: ${SERVER_SSL_KEY_ALIAS}
r8n:
  security:
    jwt:
      private-key: ${JWT_PRIVATE_KEY}
      public-key: ${JWT_PUBLIC_KEY}
