server:
  port: ${GATEWAY_PORT}
  ssl:
    enabled: ${SERVER_SSL_ENABLED}
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE}
    key-alias: ${SERVER_SSL_KEY_ALIAS}

spring:
  application.name: gateway-sv
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: block_internal
              uri: no-forward://internal
              predicates:
                - Path=/api/internal/**
              filters:
                - SetStatus=403
            - id: auth
              uri: ${INTERSERVICE_PROTOCOL}://${SERVICES_USERS_HOST}:${SERVICES_USERS_PORT}
              predicates:
                - Path=/api/auth/**
            - id: opinions
              uri: ${INTERSERVICE_PROTOCOL}://${SERVICES_OPINIONS_HOST}:${SERVICES_OPINIONS_PORT}
              predicates:
                - Path=/api/access-requests/**,/api/opinion-lists/**,/api/opinions/**
            - id: opinions_swagger
              uri: ${INTERSERVICE_PROTOCOL}://${SERVICES_OPINIONS_HOST}:${SERVICES_OPINIONS_PORT}
              predicates:
                - Path=/api/opinions/swagger-ui.html,/api/opinions/swagger-ui/**,/api/opinions/webjars/swagger-ui/**
              filters:
                - RewritePath=/api/opinions/(?<segment>.*), /$\{segment}
            - id: users
              uri: ${INTERSERVICE_PROTOCOL}://${SERVICES_USERS_HOST}:${SERVICES_USERS_PORT}
              predicates:
                - Path=/api/users/**
            - id: users_swagger
              uri: ${INTERSERVICE_PROTOCOL}://${SERVICES_USERS_HOST}:${SERVICES_USERS_PORT}
              predicates:
                - Path=/api/users/swagger-ui.html,/api/users/swagger-ui/**,/api/users/webjars/swagger-ui/**
              filters:
                - RewritePath=/api/users/(?<segment>.*), /$\{segment}
            - id: export
              uri: ${INTERSERVICE_PROTOCOL}://${SERVICES_EXPORT_HOST}:${SERVICES_EXPORT_PORT}
              predicates:
                - Path=/api/export/**
            - id: export_swagger
              uri: ${INTERSERVICE_PROTOCOL}://${SERVICES_EXPORT_HOST}:${SERVICES_EXPORT_PORT}
              predicates:
                - Path=/api/export/swagger-ui.html,/api/export/swagger-ui/**,/api/export/webjars/swagger-ui/**
              filters:
                - RewritePath=/api/export/(?<segment>.*), /$\{segment}
            - id: mock
              uri: ${INTERSERVICE_PROTOCOL}://${SERVICES_MOCK_HOST}:${SERVICES_MOCK_PORT}
              predicates:
                - Path=/api/selectors/**

            - id: public_opinions
              uri: ${INTERSERVICE_PROTOCOL}://${SERVICES_OPINIONS_HOST}:${SERVICES_OPINIONS_PORT}
              predicates:
                - Path=/api/public/opinions/**
              filters:
                - ApiKeyAuthenticationFilter
                - name: RateLimitingFilter
                  args:
                    limit: 100
                    durationSeconds: 60
                - RewritePath=/api/public/opinions/(?<segment>.*), /api/opinions/$\{segment}

            - id: public_users
              uri: ${INTERSERVICE_PROTOCOL}://${SERVICES_USERS_HOST}:${SERVICES_USERS_PORT}
              predicates:
                - Path=/api/public/users/**
              filters:
                - ApiKeyAuthenticationFilter
                - name: RateLimitingFilter
                  args:
                    limit: 100
                    durationSeconds: 60
                - RewritePath=/api/public/users/(?<segment>.*), /api/users/$\{segment}

r8n:
  security:
    public-paths: /api/auth/**
    jwt:
      private-key: ${JWT_PRIVATE_KEY}
      public-key: ${JWT_PUBLIC_KEY}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Opinions Service
        url: /api/opinions/v3/api-docs
      - name: Users Service
        url: /api/users/v3/api-docs
      - name: Export Service
        url: /api/export/v3/api-docs
